//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addressId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addressType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="recipientNm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="addressNr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="additionalInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quarter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="countryId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postalCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="postalCdIntl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="friendlyNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="addressExtraField1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addressExtraField2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="addressExtraField3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="buildingNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="floor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="digicode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lift" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="intercom" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "address", propOrder = {
    "addressId",
    "addressType",
    "recipientNm",
    "address",
    "addressNr",
    "additionalInfo",
    "quarter",
    "city",
    "state",
    "countryId",
    "postalCd",
    "postalCdIntl",
    "reference",
    "friendlyNm",
    "createDt",
    "addressExtraField1",
    "addressExtraField2",
    "addressExtraField3",
    "buildingNm",
    "floor",
    "digicode",
    "lift",
    "intercom"
})
public class Address
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String addressId;
    @XmlElement(required = true)
    protected String addressType;
    @XmlElement(required = true)
    protected String recipientNm;
    @XmlElement(required = true)
    protected String address;
    @XmlElement(required = true)
    protected String addressNr;
    protected String additionalInfo;
    @XmlElement(required = true)
    protected String quarter;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected String countryId;
    @XmlElement(required = true)
    protected String postalCd;
    protected String postalCdIntl;
    protected String reference;
    protected String friendlyNm;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDt;
    protected String addressExtraField1;
    protected String addressExtraField2;
    protected String addressExtraField3;
    protected String buildingNm;
    protected String floor;
    protected String digicode;
    protected Boolean lift;
    protected Boolean intercom;

    /**
     * Gets the value of the addressId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * Sets the value of the addressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressId(String value) {
        this.addressId = value;
    }

    public boolean isSetAddressId() {
        return (this.addressId!= null);
    }

    /**
     * Gets the value of the addressType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * Sets the value of the addressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressType(String value) {
        this.addressType = value;
    }

    public boolean isSetAddressType() {
        return (this.addressType!= null);
    }

    /**
     * Gets the value of the recipientNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientNm() {
        return recipientNm;
    }

    /**
     * Sets the value of the recipientNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientNm(String value) {
        this.recipientNm = value;
    }

    public boolean isSetRecipientNm() {
        return (this.recipientNm!= null);
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    public boolean isSetAddress() {
        return (this.address!= null);
    }

    /**
     * Gets the value of the addressNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressNr() {
        return addressNr;
    }

    /**
     * Sets the value of the addressNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressNr(String value) {
        this.addressNr = value;
    }

    public boolean isSetAddressNr() {
        return (this.addressNr!= null);
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfo(String value) {
        this.additionalInfo = value;
    }

    public boolean isSetAdditionalInfo() {
        return (this.additionalInfo!= null);
    }

    /**
     * Gets the value of the quarter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuarter() {
        return quarter;
    }

    /**
     * Sets the value of the quarter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuarter(String value) {
        this.quarter = value;
    }

    public boolean isSetQuarter() {
        return (this.quarter!= null);
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    public boolean isSetCity() {
        return (this.city!= null);
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    public boolean isSetState() {
        return (this.state!= null);
    }

    /**
     * Gets the value of the countryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * Sets the value of the countryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryId(String value) {
        this.countryId = value;
    }

    public boolean isSetCountryId() {
        return (this.countryId!= null);
    }

    /**
     * Gets the value of the postalCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCd() {
        return postalCd;
    }

    /**
     * Sets the value of the postalCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCd(String value) {
        this.postalCd = value;
    }

    public boolean isSetPostalCd() {
        return (this.postalCd!= null);
    }

    /**
     * Gets the value of the postalCdIntl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCdIntl() {
        return postalCdIntl;
    }

    /**
     * Sets the value of the postalCdIntl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCdIntl(String value) {
        this.postalCdIntl = value;
    }

    public boolean isSetPostalCdIntl() {
        return (this.postalCdIntl!= null);
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        this.reference = value;
    }

    public boolean isSetReference() {
        return (this.reference!= null);
    }

    /**
     * Gets the value of the friendlyNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFriendlyNm() {
        return friendlyNm;
    }

    /**
     * Sets the value of the friendlyNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFriendlyNm(String value) {
        this.friendlyNm = value;
    }

    public boolean isSetFriendlyNm() {
        return (this.friendlyNm!= null);
    }

    /**
     * Gets the value of the createDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDt() {
        return createDt;
    }

    /**
     * Sets the value of the createDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDt(XMLGregorianCalendar value) {
        this.createDt = value;
    }

    public boolean isSetCreateDt() {
        return (this.createDt!= null);
    }

    /**
     * Gets the value of the addressExtraField1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressExtraField1() {
        return addressExtraField1;
    }

    /**
     * Sets the value of the addressExtraField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressExtraField1(String value) {
        this.addressExtraField1 = value;
    }

    public boolean isSetAddressExtraField1() {
        return (this.addressExtraField1 != null);
    }

    /**
     * Gets the value of the addressExtraField2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressExtraField2() {
        return addressExtraField2;
    }

    /**
     * Sets the value of the addressExtraField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressExtraField2(String value) {
        this.addressExtraField2 = value;
    }

    public boolean isSetAddressExtraField2() {
        return (this.addressExtraField2 != null);
    }

    /**
     * Gets the value of the addressExtraField3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressExtraField3() {
        return addressExtraField3;
    }

    /**
     * Sets the value of the addressExtraField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressExtraField3(String value) {
        this.addressExtraField3 = value;
    }

    public boolean isSetAddressExtraField3() {
        return (this.addressExtraField3 != null);
    }

    /**
     * Gets the value of the buildingNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildingNm() {
        return buildingNm;
    }

    /**
     * Sets the value of the buildingNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildingNm(String value) {
        this.buildingNm = value;
    }

    public boolean isSetBuildingNm() {
        return (this.buildingNm!= null);
    }

    /**
     * Gets the value of the floor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloor(String value) {
        this.floor = value;
    }

    public boolean isSetFloor() {
        return (this.floor!= null);
    }

    /**
     * Gets the value of the digicode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigicode() {
        return digicode;
    }

    /**
     * Sets the value of the digicode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigicode(String value) {
        this.digicode = value;
    }

    public boolean isSetDigicode() {
        return (this.digicode!= null);
    }

    /**
     * Gets the value of the lift property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLift() {
        return lift;
    }

    /**
     * Sets the value of the lift property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLift(Boolean value) {
        this.lift = value;
    }

    public boolean isSetLift() {
        return (this.lift!= null);
    }

    /**
     * Gets the value of the intercom property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIntercom() {
        return intercom;
    }

    /**
     * Sets the value of the intercom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIntercom(Boolean value) {
        this.intercom = value;
    }

    public boolean isSetIntercom() {
        return (this.intercom!= null);
    }

}
