//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for cieloPayment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cieloPayment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.accurate.com/acec/order}abstractPayment">
 *       &lt;sequence>
 *         &lt;element name="approvalCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="approvalDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="eci" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="lr" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="arp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nsu" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardHoldersName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encriptedCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encriptedExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encriptedCardSecurityCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maskedCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardVerificationCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cieloPayment", propOrder = {
    "approvalCode",
    "approvalDateTime",
    "eci",
    "lr",
    "arp",
    "pan",
    "nsu",
    "cardHoldersName",
    "brand",
    "encriptedCardNumber",
    "encriptedExpirationDate",
    "encriptedCardSecurityCode",
    "maskedCardNumber",
    "cardVerificationCode"
})
public class CieloPayment
    extends AbstractPayment
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected BigInteger approvalCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar approvalDateTime;
    @XmlElement(required = true)
    protected BigInteger eci;
    @XmlElement(required = true)
    protected BigInteger lr;
    @XmlElement(required = true)
    protected String arp;
    @XmlElement(required = true)
    protected String pan;
    @XmlElement(required = true)
    protected String nsu;
    @XmlElement(required = true)
    protected String cardHoldersName;
    @XmlElement(required = true)
    protected String brand;
    @XmlElement(required = true)
    protected String encriptedCardNumber;
    @XmlElement(required = true)
    protected String encriptedExpirationDate;
    protected String encriptedCardSecurityCode;
    @XmlElement(required = true)
    protected String maskedCardNumber;
    @XmlElement(required = true)
    protected BigInteger cardVerificationCode;

    /**
     * Gets the value of the approvalCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getApprovalCode() {
        return approvalCode;
    }

    /**
     * Sets the value of the approvalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setApprovalCode(BigInteger value) {
        this.approvalCode = value;
    }

    public boolean isSetApprovalCode() {
        return (this.approvalCode!= null);
    }

    /**
     * Gets the value of the approvalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApprovalDateTime() {
        return approvalDateTime;
    }

    /**
     * Sets the value of the approvalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApprovalDateTime(XMLGregorianCalendar value) {
        this.approvalDateTime = value;
    }

    public boolean isSetApprovalDateTime() {
        return (this.approvalDateTime!= null);
    }

    /**
     * Gets the value of the eci property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEci() {
        return eci;
    }

    /**
     * Sets the value of the eci property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEci(BigInteger value) {
        this.eci = value;
    }

    public boolean isSetEci() {
        return (this.eci!= null);
    }

    /**
     * Gets the value of the lr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLr() {
        return lr;
    }

    /**
     * Sets the value of the lr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLr(BigInteger value) {
        this.lr = value;
    }

    public boolean isSetLr() {
        return (this.lr!= null);
    }

    /**
     * Gets the value of the arp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArp() {
        return arp;
    }

    /**
     * Sets the value of the arp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArp(String value) {
        this.arp = value;
    }

    public boolean isSetArp() {
        return (this.arp!= null);
    }

    /**
     * Gets the value of the pan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPan() {
        return pan;
    }

    /**
     * Sets the value of the pan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPan(String value) {
        this.pan = value;
    }

    public boolean isSetPan() {
        return (this.pan!= null);
    }

    /**
     * Gets the value of the nsu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNsu() {
        return nsu;
    }

    /**
     * Sets the value of the nsu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNsu(String value) {
        this.nsu = value;
    }

    public boolean isSetNsu() {
        return (this.nsu!= null);
    }

    /**
     * Gets the value of the cardHoldersName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHoldersName() {
        return cardHoldersName;
    }

    /**
     * Sets the value of the cardHoldersName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHoldersName(String value) {
        this.cardHoldersName = value;
    }

    public boolean isSetCardHoldersName() {
        return (this.cardHoldersName!= null);
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    public boolean isSetBrand() {
        return (this.brand!= null);
    }

    /**
     * Gets the value of the encriptedCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncriptedCardNumber() {
        return encriptedCardNumber;
    }

    /**
     * Sets the value of the encriptedCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncriptedCardNumber(String value) {
        this.encriptedCardNumber = value;
    }

    public boolean isSetEncriptedCardNumber() {
        return (this.encriptedCardNumber!= null);
    }

    /**
     * Gets the value of the encriptedExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncriptedExpirationDate() {
        return encriptedExpirationDate;
    }

    /**
     * Sets the value of the encriptedExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncriptedExpirationDate(String value) {
        this.encriptedExpirationDate = value;
    }

    public boolean isSetEncriptedExpirationDate() {
        return (this.encriptedExpirationDate!= null);
    }

    /**
     * Gets the value of the encriptedCardSecurityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncriptedCardSecurityCode() {
        return encriptedCardSecurityCode;
    }

    /**
     * Sets the value of the encriptedCardSecurityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncriptedCardSecurityCode(String value) {
        this.encriptedCardSecurityCode = value;
    }

    public boolean isSetEncriptedCardSecurityCode() {
        return (this.encriptedCardSecurityCode!= null);
    }

    /**
     * Gets the value of the maskedCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaskedCardNumber() {
        return maskedCardNumber;
    }

    /**
     * Sets the value of the maskedCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaskedCardNumber(String value) {
        this.maskedCardNumber = value;
    }

    public boolean isSetMaskedCardNumber() {
        return (this.maskedCardNumber!= null);
    }

    /**
     * Gets the value of the cardVerificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCardVerificationCode() {
        return cardVerificationCode;
    }

    /**
     * Sets the value of the cardVerificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCardVerificationCode(BigInteger value) {
        this.cardVerificationCode = value;
    }

    public boolean isSetCardVerificationCode() {
        return (this.cardVerificationCode!= null);
    }

}
