//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for creditCardPayment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creditCardPayment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.accurate.com/acec/order}abstractPayment">
 *       &lt;sequence>
 *         &lt;element name="cardHoldersName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="numberOfInstallments" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="encriptedCreditCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encriptedExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encriptedCardSecurityCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maskedCreditCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardVerificationCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creditCardPayment", propOrder = {
    "cardHoldersName",
    "brand",
    "numberOfInstallments",
    "encriptedCreditCardNumber",
    "encriptedExpirationDate",
    "encriptedCardSecurityCode",
    "maskedCreditCardNumber",
    "cardVerificationCode"
})
public class CreditCardPayment
    extends AbstractPayment
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String cardHoldersName;
    @XmlElement(required = true)
    protected String brand;
    @XmlElement(required = true)
    protected BigInteger numberOfInstallments;
    @XmlElement(required = true)
    protected String encriptedCreditCardNumber;
    @XmlElement(required = true)
    protected String encriptedExpirationDate;
    protected String encriptedCardSecurityCode;
    @XmlElement(required = true)
    protected String maskedCreditCardNumber;
    @XmlElement(required = true)
    protected BigInteger cardVerificationCode;

    /**
     * Gets the value of the cardHoldersName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHoldersName() {
        return cardHoldersName;
    }

    /**
     * Sets the value of the cardHoldersName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHoldersName(String value) {
        this.cardHoldersName = value;
    }

    public boolean isSetCardHoldersName() {
        return (this.cardHoldersName!= null);
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    public boolean isSetBrand() {
        return (this.brand!= null);
    }

    /**
     * Gets the value of the numberOfInstallments property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfInstallments() {
        return numberOfInstallments;
    }

    /**
     * Sets the value of the numberOfInstallments property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfInstallments(BigInteger value) {
        this.numberOfInstallments = value;
    }

    public boolean isSetNumberOfInstallments() {
        return (this.numberOfInstallments!= null);
    }

    /**
     * Gets the value of the encriptedCreditCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncriptedCreditCardNumber() {
        return encriptedCreditCardNumber;
    }

    /**
     * Sets the value of the encriptedCreditCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncriptedCreditCardNumber(String value) {
        this.encriptedCreditCardNumber = value;
    }

    public boolean isSetEncriptedCreditCardNumber() {
        return (this.encriptedCreditCardNumber!= null);
    }

    /**
     * Gets the value of the encriptedExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncriptedExpirationDate() {
        return encriptedExpirationDate;
    }

    /**
     * Sets the value of the encriptedExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncriptedExpirationDate(String value) {
        this.encriptedExpirationDate = value;
    }

    public boolean isSetEncriptedExpirationDate() {
        return (this.encriptedExpirationDate!= null);
    }

    /**
     * Gets the value of the encriptedCardSecurityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncriptedCardSecurityCode() {
        return encriptedCardSecurityCode;
    }

    /**
     * Sets the value of the encriptedCardSecurityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncriptedCardSecurityCode(String value) {
        this.encriptedCardSecurityCode = value;
    }

    public boolean isSetEncriptedCardSecurityCode() {
        return (this.encriptedCardSecurityCode!= null);
    }

    /**
     * Gets the value of the maskedCreditCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaskedCreditCardNumber() {
        return maskedCreditCardNumber;
    }

    /**
     * Sets the value of the maskedCreditCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaskedCreditCardNumber(String value) {
        this.maskedCreditCardNumber = value;
    }

    public boolean isSetMaskedCreditCardNumber() {
        return (this.maskedCreditCardNumber!= null);
    }

    /**
     * Gets the value of the cardVerificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCardVerificationCode() {
        return cardVerificationCode;
    }

    /**
     * Sets the value of the cardVerificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCardVerificationCode(BigInteger value) {
        this.cardVerificationCode = value;
    }

    public boolean isSetCardVerificationCode() {
        return (this.cardVerificationCode!= null);
    }

}
