//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerClassification" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneMobile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneHome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phoneOffice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="M"/>
 *               &lt;enumeration value="F"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="birthDt" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="state_subscription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="representativeNm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="updateDt" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="optIn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="partnerOptIn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="smsOptIn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="smsTrackingOptIn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="customerLoyaltyList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="customerLoyalty" type="{http://www.accurate.com/acec/order}customerLoyalty" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="documentRegisterNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="documentRegisterEmissionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="documentRegisterEmissor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="occupation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="salaryRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nationality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="motherName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="guest" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customer", propOrder = {
    "customerId",
    "documentNumber",
    "customerClassification",
    "customerType",
    "name",
    "lastName",
    "email",
    "phoneMobile",
    "phoneHome",
    "phoneOffice",
    "gender",
    "birthDt",
    "stateSubscription",
    "representativeNm",
    "createDt",
    "updateDt",
    "title",
    "optIn",
    "partnerOptIn",
    "smsOptIn",
    "smsTrackingOptIn",
    "customerLoyaltyList",
    "documentRegisterNumber",
    "documentRegisterEmissionDate",
    "documentRegisterEmissor",
    "occupation",
    "salaryRange",
    "maritalStatus",
    "nationality",
    "motherName",
    "guest"
})
public class Customer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String customerId;
    @XmlElement(required = true)
    protected String documentNumber;
    @XmlElement(required = true)
    protected String customerClassification;
    @XmlElement(required = true)
    protected String customerType;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String lastName;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String phoneMobile;
    @XmlElement(required = true)
    protected String phoneHome;
    @XmlElement(required = true)
    protected String phoneOffice;
    @XmlElement(required = true)
    protected String gender;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar birthDt;
    @XmlElement(name = "state_subscription")
    protected String stateSubscription;
    protected String representativeNm;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createDt;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updateDt;
    @XmlElement(required = true)
    protected String title;
    protected Boolean optIn;
    protected Boolean partnerOptIn;
    protected Boolean smsOptIn;
    protected Boolean smsTrackingOptIn;
    @XmlElement(required = true)
    protected Customer.CustomerLoyaltyList customerLoyaltyList;
    protected String documentRegisterNumber;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar documentRegisterEmissionDate;
    protected String documentRegisterEmissor;
    protected String occupation;
    protected String salaryRange;
    protected String maritalStatus;
    protected String nationality;
    protected String motherName;
    protected String guest;

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    public boolean isSetCustomerId() {
        return (this.customerId!= null);
    }

    /**
     * Gets the value of the documentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentNumber() {
        return documentNumber;
    }

    /**
     * Sets the value of the documentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentNumber(String value) {
        this.documentNumber = value;
    }

    public boolean isSetDocumentNumber() {
        return (this.documentNumber!= null);
    }

    /**
     * Gets the value of the customerClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerClassification() {
        return customerClassification;
    }

    /**
     * Sets the value of the customerClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerClassification(String value) {
        this.customerClassification = value;
    }

    public boolean isSetCustomerClassification() {
        return (this.customerClassification!= null);
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerType(String value) {
        this.customerType = value;
    }

    public boolean isSetCustomerType() {
        return (this.customerType!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    public boolean isSetLastName() {
        return (this.lastName!= null);
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    public boolean isSetEmail() {
        return (this.email!= null);
    }

    /**
     * Gets the value of the phoneMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneMobile() {
        return phoneMobile;
    }

    /**
     * Sets the value of the phoneMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneMobile(String value) {
        this.phoneMobile = value;
    }

    public boolean isSetPhoneMobile() {
        return (this.phoneMobile!= null);
    }

    /**
     * Gets the value of the phoneHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneHome() {
        return phoneHome;
    }

    /**
     * Sets the value of the phoneHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneHome(String value) {
        this.phoneHome = value;
    }

    public boolean isSetPhoneHome() {
        return (this.phoneHome!= null);
    }

    /**
     * Gets the value of the phoneOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneOffice() {
        return phoneOffice;
    }

    /**
     * Sets the value of the phoneOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneOffice(String value) {
        this.phoneOffice = value;
    }

    public boolean isSetPhoneOffice() {
        return (this.phoneOffice!= null);
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    public boolean isSetGender() {
        return (this.gender!= null);
    }

    /**
     * Gets the value of the birthDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDt() {
        return birthDt;
    }

    /**
     * Sets the value of the birthDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDt(XMLGregorianCalendar value) {
        this.birthDt = value;
    }

    public boolean isSetBirthDt() {
        return (this.birthDt!= null);
    }

    /**
     * Gets the value of the stateSubscription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateSubscription() {
        return stateSubscription;
    }

    /**
     * Sets the value of the stateSubscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateSubscription(String value) {
        this.stateSubscription = value;
    }

    public boolean isSetStateSubscription() {
        return (this.stateSubscription!= null);
    }

    /**
     * Gets the value of the representativeNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentativeNm() {
        return representativeNm;
    }

    /**
     * Sets the value of the representativeNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentativeNm(String value) {
        this.representativeNm = value;
    }

    public boolean isSetRepresentativeNm() {
        return (this.representativeNm!= null);
    }

    /**
     * Gets the value of the createDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateDt() {
        return createDt;
    }

    /**
     * Sets the value of the createDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateDt(XMLGregorianCalendar value) {
        this.createDt = value;
    }

    public boolean isSetCreateDt() {
        return (this.createDt!= null);
    }

    /**
     * Gets the value of the updateDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdateDt() {
        return updateDt;
    }

    /**
     * Sets the value of the updateDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdateDt(XMLGregorianCalendar value) {
        this.updateDt = value;
    }

    public boolean isSetUpdateDt() {
        return (this.updateDt!= null);
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    public boolean isSetTitle() {
        return (this.title!= null);
    }

    /**
     * Gets the value of the optIn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOptIn() {
        return optIn;
    }

    /**
     * Sets the value of the optIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOptIn(Boolean value) {
        this.optIn = value;
    }

    public boolean isSetOptIn() {
        return (this.optIn!= null);
    }

    /**
     * Gets the value of the partnerOptIn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPartnerOptIn() {
        return partnerOptIn;
    }

    /**
     * Sets the value of the partnerOptIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPartnerOptIn(Boolean value) {
        this.partnerOptIn = value;
    }

    public boolean isSetPartnerOptIn() {
        return (this.partnerOptIn!= null);
    }

    /**
     * Gets the value of the smsOptIn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmsOptIn() {
        return smsOptIn;
    }

    /**
     * Sets the value of the smsOptIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmsOptIn(Boolean value) {
        this.smsOptIn = value;
    }

    public boolean isSetSmsOptIn() {
        return (this.smsOptIn!= null);
    }

    /**
     * Gets the value of the smsTrackingOptIn property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSmsTrackingOptIn() {
        return smsTrackingOptIn;
    }

    /**
     * Sets the value of the smsTrackingOptIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSmsTrackingOptIn(Boolean value) {
        this.smsTrackingOptIn = value;
    }

    public boolean isSetSmsTrackingOptIn() {
        return (this.smsTrackingOptIn!= null);
    }

    /**
     * Gets the value of the customerLoyaltyList property.
     * 
     * @return
     *     possible object is
     *     {@link Customer.CustomerLoyaltyList }
     *     
     */
    public Customer.CustomerLoyaltyList getCustomerLoyaltyList() {
        return customerLoyaltyList;
    }

    /**
     * Sets the value of the customerLoyaltyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer.CustomerLoyaltyList }
     *     
     */
    public void setCustomerLoyaltyList(Customer.CustomerLoyaltyList value) {
        this.customerLoyaltyList = value;
    }

    public boolean isSetCustomerLoyaltyList() {
        return (this.customerLoyaltyList!= null);
    }

    /**
     * Gets the value of the documentRegisterNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentRegisterNumber() {
        return documentRegisterNumber;
    }

    /**
     * Sets the value of the documentRegisterNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentRegisterNumber(String value) {
        this.documentRegisterNumber = value;
    }

    public boolean isSetDocumentRegisterNumber() {
        return (this.documentRegisterNumber!= null);
    }

    /**
     * Gets the value of the documentRegisterEmissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDocumentRegisterEmissionDate() {
        return documentRegisterEmissionDate;
    }

    /**
     * Sets the value of the documentRegisterEmissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDocumentRegisterEmissionDate(XMLGregorianCalendar value) {
        this.documentRegisterEmissionDate = value;
    }

    public boolean isSetDocumentRegisterEmissionDate() {
        return (this.documentRegisterEmissionDate!= null);
    }

    /**
     * Gets the value of the documentRegisterEmissor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentRegisterEmissor() {
        return documentRegisterEmissor;
    }

    /**
     * Sets the value of the documentRegisterEmissor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentRegisterEmissor(String value) {
        this.documentRegisterEmissor = value;
    }

    public boolean isSetDocumentRegisterEmissor() {
        return (this.documentRegisterEmissor!= null);
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

    public boolean isSetOccupation() {
        return (this.occupation!= null);
    }

    /**
     * Gets the value of the salaryRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalaryRange() {
        return salaryRange;
    }

    /**
     * Sets the value of the salaryRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalaryRange(String value) {
        this.salaryRange = value;
    }

    public boolean isSetSalaryRange() {
        return (this.salaryRange!= null);
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    public boolean isSetMaritalStatus() {
        return (this.maritalStatus!= null);
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNationality(String value) {
        this.nationality = value;
    }

    public boolean isSetNationality() {
        return (this.nationality!= null);
    }

    /**
     * Gets the value of the motherName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotherName() {
        return motherName;
    }

    /**
     * Sets the value of the motherName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotherName(String value) {
        this.motherName = value;
    }

    public boolean isSetMotherName() {
        return (this.motherName!= null);
    }

    /**
     * Gets the value of the guest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuest() {
        return guest;
    }

    /**
     * Sets the value of the guest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuest(String value) {
        this.guest = value;
    }

    public boolean isSetGuest() {
        return (this.guest!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="customerLoyalty" type="{http://www.accurate.com/acec/order}customerLoyalty" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customerLoyalty"
    })
    public static class CustomerLoyaltyList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<CustomerLoyalty> customerLoyalty;

        /**
         * Gets the value of the customerLoyalty property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customerLoyalty property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomerLoyalty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CustomerLoyalty }
         * 
         * 
         */
        public List<CustomerLoyalty> getCustomerLoyalty() {
            if (customerLoyalty == null) {
                customerLoyalty = new ArrayList<CustomerLoyalty>();
            }
            return this.customerLoyalty;
        }

        public boolean isSetCustomerLoyalty() {
            return ((this.customerLoyalty!= null)&&(!this.customerLoyalty.isEmpty()));
        }

        public void unsetCustomerLoyalty() {
            this.customerLoyalty = null;
        }

    }

}
