//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for freight complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="freight">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chargedAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="actualAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="commercialAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="freightTime" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="pickupLeadTime" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="logisticContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="expectedDeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="adjustedDeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "freight", propOrder = {
    "chargedAmount",
    "actualAmount",
    "commercialAmount",
    "freightTime",
    "pickupLeadTime",
    "logisticContract",
    "expectedDeliveryDate",
    "adjustedDeliveryDate"
})
public class Freight
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected BigDecimal chargedAmount;
    protected BigDecimal actualAmount;
    protected BigDecimal commercialAmount;
    protected BigInteger freightTime;
    protected BigInteger pickupLeadTime;
    protected String logisticContract;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expectedDeliveryDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar adjustedDeliveryDate;

    /**
     * Gets the value of the chargedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getChargedAmount() {
        return chargedAmount;
    }

    /**
     * Sets the value of the chargedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setChargedAmount(BigDecimal value) {
        this.chargedAmount = value;
    }

    public boolean isSetChargedAmount() {
        return (this.chargedAmount!= null);
    }

    /**
     * Gets the value of the actualAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActualAmount() {
        return actualAmount;
    }

    /**
     * Sets the value of the actualAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActualAmount(BigDecimal value) {
        this.actualAmount = value;
    }

    public boolean isSetActualAmount() {
        return (this.actualAmount!= null);
    }

    /**
     * Gets the value of the commercialAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCommercialAmount() {
        return commercialAmount;
    }

    /**
     * Sets the value of the commercialAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCommercialAmount(BigDecimal value) {
        this.commercialAmount = value;
    }

    public boolean isSetCommercialAmount() {
        return (this.commercialAmount!= null);
    }

    /**
     * Gets the value of the freightTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreightTime() {
        return freightTime;
    }

    /**
     * Sets the value of the freightTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreightTime(BigInteger value) {
        this.freightTime = value;
    }

    public boolean isSetFreightTime() {
        return (this.freightTime!= null);
    }

    /**
     * Gets the value of the pickupLeadTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPickupLeadTime() {
        return pickupLeadTime;
    }

    /**
     * Sets the value of the pickupLeadTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPickupLeadTime(BigInteger value) {
        this.pickupLeadTime = value;
    }

    public boolean isSetPickupLeadTime() {
        return (this.pickupLeadTime!= null);
    }

    /**
     * Gets the value of the logisticContract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogisticContract() {
        return logisticContract;
    }

    /**
     * Sets the value of the logisticContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogisticContract(String value) {
        this.logisticContract = value;
    }

    public boolean isSetLogisticContract() {
        return (this.logisticContract!= null);
    }

    /**
     * Gets the value of the expectedDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpectedDeliveryDate() {
        return expectedDeliveryDate;
    }

    /**
     * Sets the value of the expectedDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpectedDeliveryDate(XMLGregorianCalendar value) {
        this.expectedDeliveryDate = value;
    }

    public boolean isSetExpectedDeliveryDate() {
        return (this.expectedDeliveryDate!= null);
    }

    /**
     * Gets the value of the adjustedDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAdjustedDeliveryDate() {
        return adjustedDeliveryDate;
    }

    /**
     * Sets the value of the adjustedDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAdjustedDeliveryDate(XMLGregorianCalendar value) {
        this.adjustedDeliveryDate = value;
    }

    public boolean isSetAdjustedDeliveryDate() {
        return (this.adjustedDeliveryDate!= null);
    }

}
