//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.accurate.acec.order package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SkuDeliveryTracking_QNAME = new QName("http://www.accurate.com/acec/order", "skuDeliveryTracking");
    private final static QName _CieloPayment_QNAME = new QName("http://www.accurate.com/acec/order", "cieloPayment");
    private final static QName _Order_QNAME = new QName("http://www.accurate.com/acec/order", "order");
    private final static QName _Deliveries_QNAME = new QName("http://www.accurate.com/acec/order", "deliveries");
    private final static QName _Tracking_QNAME = new QName("http://www.accurate.com/acec/order", "tracking");
    private final static QName _AbstractPayment_QNAME = new QName("http://www.accurate.com/acec/order", "abstractPayment");
    private final static QName _Replenishment_QNAME = new QName("http://www.accurate.com/acec/order", "replenishment");
    private final static QName _CreditCardPayment_QNAME = new QName("http://www.accurate.com/acec/order", "creditCardPayment");
    private final static QName _SipsPayment_QNAME = new QName("http://www.accurate.com/acec/order", "sipsPayment");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.accurate.acec.order
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link SlotInfo }
     * 
     */
    public SlotInfo createSlotInfo() {
        return new SlotInfo();
    }

    /**
     * Create an instance of {@link Delivery }
     * 
     */
    public Delivery createDelivery() {
        return new Delivery();
    }

    /**
     * Create an instance of {@link OrderLine }
     * 
     */
    public OrderLine createOrderLine() {
        return new OrderLine();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Tracking }
     * 
     */
    public Tracking createTracking() {
        return new Tracking();
    }

    /**
     * Create an instance of {@link AbstractPayment }
     * 
     */
    public AbstractPayment createAbstractPayment() {
        return new AbstractPayment();
    }

    /**
     * Create an instance of {@link CreditCardPayment }
     * 
     */
    public CreditCardPayment createCreditCardPayment() {
        return new CreditCardPayment();
    }

    /**
     * Create an instance of {@link SipsPayment }
     * 
     */
    public SipsPayment createSipsPayment() {
        return new SipsPayment();
    }

    /**
     * Create an instance of {@link ReplenishmentInfo }
     * 
     */
    public ReplenishmentInfo createReplenishmentInfo() {
        return new ReplenishmentInfo();
    }

    /**
     * Create an instance of {@link SkuDeliveryTracking }
     * 
     */
    public SkuDeliveryTracking createSkuDeliveryTracking() {
        return new SkuDeliveryTracking();
    }

    /**
     * Create an instance of {@link CieloPayment }
     * 
     */
    public CieloPayment createCieloPayment() {
        return new CieloPayment();
    }

    /**
     * Create an instance of {@link Deliveries }
     * 
     */
    public Deliveries createDeliveries() {
        return new Deliveries();
    }

    /**
     * Create an instance of {@link DeliveryProperty }
     * 
     */
    public DeliveryProperty createDeliveryProperty() {
        return new DeliveryProperty();
    }

    /**
     * Create an instance of {@link Freight }
     * 
     */
    public Freight createFreight() {
        return new Freight();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link OrderProperty }
     * 
     */
    public OrderProperty createOrderProperty() {
        return new OrderProperty();
    }

    /**
     * Create an instance of {@link LoyaltyCredit }
     * 
     */
    public LoyaltyCredit createLoyaltyCredit() {
        return new LoyaltyCredit();
    }

    /**
     * Create an instance of {@link ShopInfo }
     * 
     */
    public ShopInfo createShopInfo() {
        return new ShopInfo();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link TrackingProperty }
     * 
     */
    public TrackingProperty createTrackingProperty() {
        return new TrackingProperty();
    }

    /**
     * Create an instance of {@link Level }
     * 
     */
    public Level createLevel() {
        return new Level();
    }

    /**
     * Create an instance of {@link CustomerLoyalty }
     * 
     */
    public CustomerLoyalty createCustomerLoyalty() {
        return new CustomerLoyalty();
    }

    /**
     * Create an instance of {@link PaymentProperty }
     * 
     */
    public PaymentProperty createPaymentProperty() {
        return new PaymentProperty();
    }

    /**
     * Create an instance of {@link GiftCard }
     * 
     */
    public GiftCard createGiftCard() {
        return new GiftCard();
    }

    /**
     * Create an instance of {@link GiftWrap }
     * 
     */
    public GiftWrap createGiftWrap() {
        return new GiftWrap();
    }

    /**
     * Create an instance of {@link OrderLineProperty }
     * 
     */
    public OrderLineProperty createOrderLineProperty() {
        return new OrderLineProperty();
    }

    /**
     * Create an instance of {@link Promotion }
     * 
     */
    public Promotion createPromotion() {
        return new Promotion();
    }

    /**
     * Create an instance of {@link Customer.CustomerLoyaltyList }
     * 
     */
    public Customer.CustomerLoyaltyList createCustomerCustomerLoyaltyList() {
        return new Customer.CustomerLoyaltyList();
    }

    /**
     * Create an instance of {@link SlotInfo.PromotionList }
     * 
     */
    public SlotInfo.PromotionList createSlotInfoPromotionList() {
        return new SlotInfo.PromotionList();
    }

    /**
     * Create an instance of {@link Delivery.OrderLineList }
     * 
     */
    public Delivery.OrderLineList createDeliveryOrderLineList() {
        return new Delivery.OrderLineList();
    }

    /**
     * Create an instance of {@link Delivery.TrackingList }
     * 
     */
    public Delivery.TrackingList createDeliveryTrackingList() {
        return new Delivery.TrackingList();
    }

    /**
     * Create an instance of {@link Delivery.SkuDeliveryTrackingList }
     * 
     */
    public Delivery.SkuDeliveryTrackingList createDeliverySkuDeliveryTrackingList() {
        return new Delivery.SkuDeliveryTrackingList();
    }

    /**
     * Create an instance of {@link Delivery.DeliveryPropertyList }
     * 
     */
    public Delivery.DeliveryPropertyList createDeliveryDeliveryPropertyList() {
        return new Delivery.DeliveryPropertyList();
    }

    /**
     * Create an instance of {@link OrderLine.PromotionList }
     * 
     */
    public OrderLine.PromotionList createOrderLinePromotionList() {
        return new OrderLine.PromotionList();
    }

    /**
     * Create an instance of {@link OrderLine.LoyaltyCreditList }
     * 
     */
    public OrderLine.LoyaltyCreditList createOrderLineLoyaltyCreditList() {
        return new OrderLine.LoyaltyCreditList();
    }

    /**
     * Create an instance of {@link OrderLine.Reference }
     * 
     */
    public OrderLine.Reference createOrderLineReference() {
        return new OrderLine.Reference();
    }

    /**
     * Create an instance of {@link OrderLine.OrderLinePropertyList }
     * 
     */
    public OrderLine.OrderLinePropertyList createOrderLineOrderLinePropertyList() {
        return new OrderLine.OrderLinePropertyList();
    }

    /**
     * Create an instance of {@link OrderLine.ItemLevelList }
     * 
     */
    public OrderLine.ItemLevelList createOrderLineItemLevelList() {
        return new OrderLine.ItemLevelList();
    }

    /**
     * Create an instance of {@link OrderLine.ItemLevelErpList }
     * 
     */
    public OrderLine.ItemLevelErpList createOrderLineItemLevelErpList() {
        return new OrderLine.ItemLevelErpList();
    }

    /**
     * Create an instance of {@link Order.OrderPropertyList }
     * 
     */
    public Order.OrderPropertyList createOrderOrderPropertyList() {
        return new Order.OrderPropertyList();
    }

    /**
     * Create an instance of {@link Order.PaymentList }
     * 
     */
    public Order.PaymentList createOrderPaymentList() {
        return new Order.PaymentList();
    }

    /**
     * Create an instance of {@link Tracking.TrackingPropertyList }
     * 
     */
    public Tracking.TrackingPropertyList createTrackingTrackingPropertyList() {
        return new Tracking.TrackingPropertyList();
    }

    /**
     * Create an instance of {@link AbstractPayment.PaymentPropertyList }
     * 
     */
    public AbstractPayment.PaymentPropertyList createAbstractPaymentPaymentPropertyList() {
        return new AbstractPayment.PaymentPropertyList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SkuDeliveryTracking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "skuDeliveryTracking")
    public JAXBElement<SkuDeliveryTracking> createSkuDeliveryTracking(SkuDeliveryTracking value) {
        return new JAXBElement<SkuDeliveryTracking>(_SkuDeliveryTracking_QNAME, SkuDeliveryTracking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CieloPayment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "cieloPayment")
    public JAXBElement<CieloPayment> createCieloPayment(CieloPayment value) {
        return new JAXBElement<CieloPayment>(_CieloPayment_QNAME, CieloPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Order }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "order")
    public JAXBElement<Order> createOrder(Order value) {
        return new JAXBElement<Order>(_Order_QNAME, Order.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Deliveries }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "deliveries")
    public JAXBElement<Deliveries> createDeliveries(Deliveries value) {
        return new JAXBElement<Deliveries>(_Deliveries_QNAME, Deliveries.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tracking }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "tracking")
    public JAXBElement<Tracking> createTracking(Tracking value) {
        return new JAXBElement<Tracking>(_Tracking_QNAME, Tracking.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPayment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "abstractPayment")
    public JAXBElement<AbstractPayment> createAbstractPayment(AbstractPayment value) {
        return new JAXBElement<AbstractPayment>(_AbstractPayment_QNAME, AbstractPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReplenishmentInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "replenishment")
    public JAXBElement<ReplenishmentInfo> createReplenishment(ReplenishmentInfo value) {
        return new JAXBElement<ReplenishmentInfo>(_Replenishment_QNAME, ReplenishmentInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreditCardPayment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "creditCardPayment")
    public JAXBElement<CreditCardPayment> createCreditCardPayment(CreditCardPayment value) {
        return new JAXBElement<CreditCardPayment>(_CreditCardPayment_QNAME, CreditCardPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SipsPayment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/order", name = "sipsPayment")
    public JAXBElement<SipsPayment> createSipsPayment(SipsPayment value) {
        return new JAXBElement<SipsPayment>(_SipsPayment_QNAME, SipsPayment.class, null, value);
    }

}
