//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Linha do pedido
 * 
 * <p>Java class for orderLine complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderLine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderLineId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sku" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="skuIdOrigin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="skuType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="measureUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="catalogListPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="listPrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="salePrice" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="replenishmentInfo" type="{http://www.accurate.com/acec/order}replenishmentInfo" minOccurs="0"/>
 *         &lt;element name="unconditionalDiscountAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="conditionalDiscountAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="roundingDiscountAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="loyaltyCreditEarningAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="roundingLoyaltyCreditEarningAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="promotionList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="promotion" type="{http://www.accurate.com/acec/order}promotion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="loyaltyCreditList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="loyaltyCredit" type="{http://www.accurate.com/acec/order}loyaltyCredit" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="freight" type="{http://www.accurate.com/acec/order}freight"/>
 *         &lt;element name="leadTime" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="giftCard" type="{http://www.accurate.com/acec/order}giftCard" minOccurs="0"/>
 *         &lt;element name="giftWrap" type="{http://www.accurate.com/acec/order}giftWrap" minOccurs="0"/>
 *         &lt;element name="kitSkuId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kitSkuName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kitQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="reference" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="skuId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="catalogId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="catalogReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderLinePropertyList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="orderLineProperty" type="{http://www.accurate.com/acec/order}orderLineProperty" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="inventoryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="skuName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productBrandName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="itemTotalFinancialExpense" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="itemLevelList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="itemLevel" type="{http://www.accurate.com/acec/order}level" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="itemLevelErpList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="itemLevel" type="{http://www.accurate.com/acec/order}level" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderLine", propOrder = {
    "orderLineId",
    "sku",
    "skuIdOrigin",
    "skuType",
    "quantity",
    "measureUnit",
    "catalogListPrice",
    "listPrice",
    "salePrice",
    "replenishmentInfo",
    "unconditionalDiscountAmount",
    "conditionalDiscountAmount",
    "roundingDiscountAmount",
    "loyaltyCreditEarningAmount",
    "roundingLoyaltyCreditEarningAmount",
    "promotionList",
    "loyaltyCreditList",
    "freight",
    "leadTime",
    "giftCard",
    "giftWrap",
    "kitSkuId",
    "kitSkuName",
    "kitQuantity",
    "reference",
    "catalogId",
    "catalogReference",
    "orderLinePropertyList",
    "inventoryType",
    "service",
    "skuName",
    "productBrandName",
    "itemTotalFinancialExpense",
    "itemLevelList",
    "itemLevelErpList"
})
public class OrderLine
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String orderLineId;
    @XmlElement(required = true)
    protected String sku;
    @XmlElement(required = true)
    protected String skuIdOrigin;
    @XmlElement(required = true)
    protected String skuType;
    protected int quantity;
    @XmlElement(required = true)
    protected String measureUnit;
    @XmlElement(required = true)
    protected BigDecimal catalogListPrice;
    @XmlElement(required = true)
    protected BigDecimal listPrice;
    @XmlElement(required = true)
    protected BigDecimal salePrice;
    protected ReplenishmentInfo replenishmentInfo;
    @XmlElement(required = true)
    protected BigDecimal unconditionalDiscountAmount;
    @XmlElement(required = true)
    protected BigDecimal conditionalDiscountAmount;
    @XmlElement(required = true)
    protected BigDecimal roundingDiscountAmount;
    @XmlElement(required = true)
    protected BigDecimal loyaltyCreditEarningAmount;
    @XmlElement(required = true)
    protected BigDecimal roundingLoyaltyCreditEarningAmount;
    protected OrderLine.PromotionList promotionList;
    protected OrderLine.LoyaltyCreditList loyaltyCreditList;
    @XmlElement(required = true)
    protected Freight freight;
    protected Integer leadTime;
    protected GiftCard giftCard;
    protected GiftWrap giftWrap;
    protected String kitSkuId;
    protected String kitSkuName;
    protected Integer kitQuantity;
    protected OrderLine.Reference reference;
    protected String catalogId;
    protected String catalogReference;
    protected OrderLine.OrderLinePropertyList orderLinePropertyList;
    @XmlElement(required = true)
    protected String inventoryType;
    protected boolean service;
    @XmlElement(required = true)
    protected String skuName;
    protected String productBrandName;
    protected BigDecimal itemTotalFinancialExpense;
    protected OrderLine.ItemLevelList itemLevelList;
    protected OrderLine.ItemLevelErpList itemLevelErpList;

    /**
     * Gets the value of the orderLineId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderLineId() {
        return orderLineId;
    }

    /**
     * Sets the value of the orderLineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderLineId(String value) {
        this.orderLineId = value;
    }

    public boolean isSetOrderLineId() {
        return (this.orderLineId!= null);
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSku() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSku(String value) {
        this.sku = value;
    }

    public boolean isSetSku() {
        return (this.sku!= null);
    }

    /**
     * Gets the value of the skuIdOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuIdOrigin() {
        return skuIdOrigin;
    }

    /**
     * Sets the value of the skuIdOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuIdOrigin(String value) {
        this.skuIdOrigin = value;
    }

    public boolean isSetSkuIdOrigin() {
        return (this.skuIdOrigin!= null);
    }

    /**
     * Gets the value of the skuType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuType() {
        return skuType;
    }

    /**
     * Sets the value of the skuType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuType(String value) {
        this.skuType = value;
    }

    public boolean isSetSkuType() {
        return (this.skuType!= null);
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

    public boolean isSetQuantity() {
        return true;
    }

    /**
     * Gets the value of the measureUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureUnit() {
        return measureUnit;
    }

    /**
     * Sets the value of the measureUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureUnit(String value) {
        this.measureUnit = value;
    }

    public boolean isSetMeasureUnit() {
        return (this.measureUnit!= null);
    }

    /**
     * Gets the value of the catalogListPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCatalogListPrice() {
        return catalogListPrice;
    }

    /**
     * Sets the value of the catalogListPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCatalogListPrice(BigDecimal value) {
        this.catalogListPrice = value;
    }

    public boolean isSetCatalogListPrice() {
        return (this.catalogListPrice!= null);
    }

    /**
     * Gets the value of the listPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getListPrice() {
        return listPrice;
    }

    /**
     * Sets the value of the listPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setListPrice(BigDecimal value) {
        this.listPrice = value;
    }

    public boolean isSetListPrice() {
        return (this.listPrice!= null);
    }

    /**
     * Gets the value of the salePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * Sets the value of the salePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSalePrice(BigDecimal value) {
        this.salePrice = value;
    }

    public boolean isSetSalePrice() {
        return (this.salePrice!= null);
    }

    /**
     * Gets the value of the replenishmentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ReplenishmentInfo }
     *     
     */
    public ReplenishmentInfo getReplenishmentInfo() {
        return replenishmentInfo;
    }

    /**
     * Sets the value of the replenishmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplenishmentInfo }
     *     
     */
    public void setReplenishmentInfo(ReplenishmentInfo value) {
        this.replenishmentInfo = value;
    }

    public boolean isSetReplenishmentInfo() {
        return (this.replenishmentInfo!= null);
    }

    /**
     * Gets the value of the unconditionalDiscountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnconditionalDiscountAmount() {
        return unconditionalDiscountAmount;
    }

    /**
     * Sets the value of the unconditionalDiscountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnconditionalDiscountAmount(BigDecimal value) {
        this.unconditionalDiscountAmount = value;
    }

    public boolean isSetUnconditionalDiscountAmount() {
        return (this.unconditionalDiscountAmount!= null);
    }

    /**
     * Gets the value of the conditionalDiscountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getConditionalDiscountAmount() {
        return conditionalDiscountAmount;
    }

    /**
     * Sets the value of the conditionalDiscountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setConditionalDiscountAmount(BigDecimal value) {
        this.conditionalDiscountAmount = value;
    }

    public boolean isSetConditionalDiscountAmount() {
        return (this.conditionalDiscountAmount!= null);
    }

    /**
     * Gets the value of the roundingDiscountAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRoundingDiscountAmount() {
        return roundingDiscountAmount;
    }

    /**
     * Sets the value of the roundingDiscountAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRoundingDiscountAmount(BigDecimal value) {
        this.roundingDiscountAmount = value;
    }

    public boolean isSetRoundingDiscountAmount() {
        return (this.roundingDiscountAmount!= null);
    }

    /**
     * Gets the value of the loyaltyCreditEarningAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLoyaltyCreditEarningAmount() {
        return loyaltyCreditEarningAmount;
    }

    /**
     * Sets the value of the loyaltyCreditEarningAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLoyaltyCreditEarningAmount(BigDecimal value) {
        this.loyaltyCreditEarningAmount = value;
    }

    public boolean isSetLoyaltyCreditEarningAmount() {
        return (this.loyaltyCreditEarningAmount!= null);
    }

    /**
     * Gets the value of the roundingLoyaltyCreditEarningAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRoundingLoyaltyCreditEarningAmount() {
        return roundingLoyaltyCreditEarningAmount;
    }

    /**
     * Sets the value of the roundingLoyaltyCreditEarningAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRoundingLoyaltyCreditEarningAmount(BigDecimal value) {
        this.roundingLoyaltyCreditEarningAmount = value;
    }

    public boolean isSetRoundingLoyaltyCreditEarningAmount() {
        return (this.roundingLoyaltyCreditEarningAmount!= null);
    }

    /**
     * Gets the value of the promotionList property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLine.PromotionList }
     *     
     */
    public OrderLine.PromotionList getPromotionList() {
        return promotionList;
    }

    /**
     * Sets the value of the promotionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLine.PromotionList }
     *     
     */
    public void setPromotionList(OrderLine.PromotionList value) {
        this.promotionList = value;
    }

    public boolean isSetPromotionList() {
        return (this.promotionList!= null);
    }

    /**
     * Gets the value of the loyaltyCreditList property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLine.LoyaltyCreditList }
     *     
     */
    public OrderLine.LoyaltyCreditList getLoyaltyCreditList() {
        return loyaltyCreditList;
    }

    /**
     * Sets the value of the loyaltyCreditList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLine.LoyaltyCreditList }
     *     
     */
    public void setLoyaltyCreditList(OrderLine.LoyaltyCreditList value) {
        this.loyaltyCreditList = value;
    }

    public boolean isSetLoyaltyCreditList() {
        return (this.loyaltyCreditList!= null);
    }

    /**
     * Gets the value of the freight property.
     * 
     * @return
     *     possible object is
     *     {@link Freight }
     *     
     */
    public Freight getFreight() {
        return freight;
    }

    /**
     * Sets the value of the freight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Freight }
     *     
     */
    public void setFreight(Freight value) {
        this.freight = value;
    }

    public boolean isSetFreight() {
        return (this.freight!= null);
    }

    /**
     * Gets the value of the leadTime property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLeadTime() {
        return leadTime;
    }

    /**
     * Sets the value of the leadTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLeadTime(Integer value) {
        this.leadTime = value;
    }

    public boolean isSetLeadTime() {
        return (this.leadTime!= null);
    }

    /**
     * Gets the value of the giftCard property.
     * 
     * @return
     *     possible object is
     *     {@link GiftCard }
     *     
     */
    public GiftCard getGiftCard() {
        return giftCard;
    }

    /**
     * Sets the value of the giftCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link GiftCard }
     *     
     */
    public void setGiftCard(GiftCard value) {
        this.giftCard = value;
    }

    public boolean isSetGiftCard() {
        return (this.giftCard!= null);
    }

    /**
     * Gets the value of the giftWrap property.
     * 
     * @return
     *     possible object is
     *     {@link GiftWrap }
     *     
     */
    public GiftWrap getGiftWrap() {
        return giftWrap;
    }

    /**
     * Sets the value of the giftWrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link GiftWrap }
     *     
     */
    public void setGiftWrap(GiftWrap value) {
        this.giftWrap = value;
    }

    public boolean isSetGiftWrap() {
        return (this.giftWrap!= null);
    }

    /**
     * Gets the value of the kitSkuId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKitSkuId() {
        return kitSkuId;
    }

    /**
     * Sets the value of the kitSkuId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKitSkuId(String value) {
        this.kitSkuId = value;
    }

    public boolean isSetKitSkuId() {
        return (this.kitSkuId!= null);
    }

    /**
     * Gets the value of the kitSkuName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKitSkuName() {
        return kitSkuName;
    }

    /**
     * Sets the value of the kitSkuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKitSkuName(String value) {
        this.kitSkuName = value;
    }

    public boolean isSetKitSkuName() {
        return (this.kitSkuName!= null);
    }

    /**
     * Gets the value of the kitQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKitQuantity() {
        return kitQuantity;
    }

    /**
     * Sets the value of the kitQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKitQuantity(Integer value) {
        this.kitQuantity = value;
    }

    public boolean isSetKitQuantity() {
        return (this.kitQuantity!= null);
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLine.Reference }
     *     
     */
    public OrderLine.Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLine.Reference }
     *     
     */
    public void setReference(OrderLine.Reference value) {
        this.reference = value;
    }

    public boolean isSetReference() {
        return (this.reference!= null);
    }

    /**
     * Gets the value of the catalogId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogId() {
        return catalogId;
    }

    /**
     * Sets the value of the catalogId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogId(String value) {
        this.catalogId = value;
    }

    public boolean isSetCatalogId() {
        return (this.catalogId!= null);
    }

    /**
     * Gets the value of the catalogReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogReference() {
        return catalogReference;
    }

    /**
     * Sets the value of the catalogReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogReference(String value) {
        this.catalogReference = value;
    }

    public boolean isSetCatalogReference() {
        return (this.catalogReference!= null);
    }

    /**
     * Gets the value of the orderLinePropertyList property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLine.OrderLinePropertyList }
     *     
     */
    public OrderLine.OrderLinePropertyList getOrderLinePropertyList() {
        return orderLinePropertyList;
    }

    /**
     * Sets the value of the orderLinePropertyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLine.OrderLinePropertyList }
     *     
     */
    public void setOrderLinePropertyList(OrderLine.OrderLinePropertyList value) {
        this.orderLinePropertyList = value;
    }

    public boolean isSetOrderLinePropertyList() {
        return (this.orderLinePropertyList!= null);
    }

    /**
     * Gets the value of the inventoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryType() {
        return inventoryType;
    }

    /**
     * Sets the value of the inventoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryType(String value) {
        this.inventoryType = value;
    }

    public boolean isSetInventoryType() {
        return (this.inventoryType!= null);
    }

    /**
     * Gets the value of the service property.
     * 
     */
    public boolean isService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     */
    public void setService(boolean value) {
        this.service = value;
    }

    public boolean isSetService() {
        return true;
    }

    /**
     * Gets the value of the skuName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * Sets the value of the skuName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkuName(String value) {
        this.skuName = value;
    }

    public boolean isSetSkuName() {
        return (this.skuName!= null);
    }

    /**
     * Gets the value of the productBrandName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductBrandName() {
        return productBrandName;
    }

    /**
     * Sets the value of the productBrandName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductBrandName(String value) {
        this.productBrandName = value;
    }

    public boolean isSetProductBrandName() {
        return (this.productBrandName!= null);
    }

    /**
     * Gets the value of the itemTotalFinancialExpense property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemTotalFinancialExpense() {
        return itemTotalFinancialExpense;
    }

    /**
     * Sets the value of the itemTotalFinancialExpense property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemTotalFinancialExpense(BigDecimal value) {
        this.itemTotalFinancialExpense = value;
    }

    public boolean isSetItemTotalFinancialExpense() {
        return (this.itemTotalFinancialExpense!= null);
    }

    /**
     * Gets the value of the itemLevelList property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLine.ItemLevelList }
     *     
     */
    public OrderLine.ItemLevelList getItemLevelList() {
        return itemLevelList;
    }

    /**
     * Sets the value of the itemLevelList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLine.ItemLevelList }
     *     
     */
    public void setItemLevelList(OrderLine.ItemLevelList value) {
        this.itemLevelList = value;
    }

    public boolean isSetItemLevelList() {
        return (this.itemLevelList!= null);
    }

    /**
     * Gets the value of the itemLevelErpList property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLine.ItemLevelErpList }
     *     
     */
    public OrderLine.ItemLevelErpList getItemLevelErpList() {
        return itemLevelErpList;
    }

    /**
     * Sets the value of the itemLevelErpList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLine.ItemLevelErpList }
     *     
     */
    public void setItemLevelErpList(OrderLine.ItemLevelErpList value) {
        this.itemLevelErpList = value;
    }

    public boolean isSetItemLevelErpList() {
        return (this.itemLevelErpList!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="itemLevel" type="{http://www.accurate.com/acec/order}level" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemLevel"
    })
    public static class ItemLevelErpList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<Level> itemLevel;

        /**
         * Gets the value of the itemLevel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the itemLevel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItemLevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Level }
         * 
         * 
         */
        public List<Level> getItemLevel() {
            if (itemLevel == null) {
                itemLevel = new ArrayList<Level>();
            }
            return this.itemLevel;
        }

        public boolean isSetItemLevel() {
            return ((this.itemLevel!= null)&&(!this.itemLevel.isEmpty()));
        }

        public void unsetItemLevel() {
            this.itemLevel = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="itemLevel" type="{http://www.accurate.com/acec/order}level" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemLevel"
    })
    public static class ItemLevelList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<Level> itemLevel;

        /**
         * Gets the value of the itemLevel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the itemLevel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItemLevel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Level }
         * 
         * 
         */
        public List<Level> getItemLevel() {
            if (itemLevel == null) {
                itemLevel = new ArrayList<Level>();
            }
            return this.itemLevel;
        }

        public boolean isSetItemLevel() {
            return ((this.itemLevel!= null)&&(!this.itemLevel.isEmpty()));
        }

        public void unsetItemLevel() {
            this.itemLevel = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="loyaltyCredit" type="{http://www.accurate.com/acec/order}loyaltyCredit" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "loyaltyCredit"
    })
    public static class LoyaltyCreditList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<LoyaltyCredit> loyaltyCredit;

        /**
         * Gets the value of the loyaltyCredit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the loyaltyCredit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLoyaltyCredit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LoyaltyCredit }
         * 
         * 
         */
        public List<LoyaltyCredit> getLoyaltyCredit() {
            if (loyaltyCredit == null) {
                loyaltyCredit = new ArrayList<LoyaltyCredit>();
            }
            return this.loyaltyCredit;
        }

        public boolean isSetLoyaltyCredit() {
            return ((this.loyaltyCredit!= null)&&(!this.loyaltyCredit.isEmpty()));
        }

        public void unsetLoyaltyCredit() {
            this.loyaltyCredit = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="orderLineProperty" type="{http://www.accurate.com/acec/order}orderLineProperty" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderLineProperty"
    })
    public static class OrderLinePropertyList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<OrderLineProperty> orderLineProperty;

        /**
         * Gets the value of the orderLineProperty property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orderLineProperty property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrderLineProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderLineProperty }
         * 
         * 
         */
        public List<OrderLineProperty> getOrderLineProperty() {
            if (orderLineProperty == null) {
                orderLineProperty = new ArrayList<OrderLineProperty>();
            }
            return this.orderLineProperty;
        }

        public boolean isSetOrderLineProperty() {
            return ((this.orderLineProperty!= null)&&(!this.orderLineProperty.isEmpty()));
        }

        public void unsetOrderLineProperty() {
            this.orderLineProperty = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="promotion" type="{http://www.accurate.com/acec/order}promotion" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "promotion"
    })
    public static class PromotionList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<Promotion> promotion;

        /**
         * Gets the value of the promotion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the promotion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPromotion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Promotion }
         * 
         * 
         */
        public List<Promotion> getPromotion() {
            if (promotion == null) {
                promotion = new ArrayList<Promotion>();
            }
            return this.promotion;
        }

        public boolean isSetPromotion() {
            return ((this.promotion!= null)&&(!this.promotion.isEmpty()));
        }

        public void unsetPromotion() {
            this.promotion = null;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="skuId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "skuId"
    })
    public static class Reference
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(required = true)
        protected List<String> skuId;

        /**
         * Gets the value of the skuId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the skuId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSkuId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSkuId() {
            if (skuId == null) {
                skuId = new ArrayList<String>();
            }
            return this.skuId;
        }

        public boolean isSetSkuId() {
            return ((this.skuId!= null)&&(!this.skuId.isEmpty()));
        }

        public void unsetSkuId() {
            this.skuId = null;
        }

    }

}
