//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderProperty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderPropertyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="orderPropertyValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderProperty", propOrder = {
    "orderPropertyId",
    "orderPropertyValue"
})
public class OrderProperty
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String orderPropertyId;
    @XmlElement(required = true)
    protected String orderPropertyValue;

    /**
     * Gets the value of the orderPropertyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderPropertyId() {
        return orderPropertyId;
    }

    /**
     * Sets the value of the orderPropertyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderPropertyId(String value) {
        this.orderPropertyId = value;
    }

    public boolean isSetOrderPropertyId() {
        return (this.orderPropertyId!= null);
    }

    /**
     * Gets the value of the orderPropertyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderPropertyValue() {
        return orderPropertyValue;
    }

    /**
     * Sets the value of the orderPropertyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderPropertyValue(String value) {
        this.orderPropertyValue = value;
    }

    public boolean isSetOrderPropertyValue() {
        return (this.orderPropertyValue!= null);
    }

}
