//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paymentProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paymentProperty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="paymentPropertyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentPropertyValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paymentProperty", propOrder = {
    "paymentPropertyId",
    "paymentPropertyValue"
})
public class PaymentProperty
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String paymentPropertyId;
    @XmlElement(required = true)
    protected String paymentPropertyValue;

    /**
     * Gets the value of the paymentPropertyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentPropertyId() {
        return paymentPropertyId;
    }

    /**
     * Sets the value of the paymentPropertyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentPropertyId(String value) {
        this.paymentPropertyId = value;
    }

    public boolean isSetPaymentPropertyId() {
        return (this.paymentPropertyId!= null);
    }

    /**
     * Gets the value of the paymentPropertyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentPropertyValue() {
        return paymentPropertyValue;
    }

    /**
     * Sets the value of the paymentPropertyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentPropertyValue(String value) {
        this.paymentPropertyValue = value;
    }

    public boolean isSetPaymentPropertyValue() {
        return (this.paymentPropertyValue!= null);
    }

}
