//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sipsPayment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sipsPayment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.accurate.com/acec/order}abstractPayment">
 *       &lt;sequence>
 *         &lt;element name="authorizationId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankResponseCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="maskedCreditCardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cvvFlag" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="cvvResponseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentCertificate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="paymentDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="billingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="responseCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transactionCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transmitionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sipsPayment", propOrder = {
    "authorizationId",
    "bankResponseCode",
    "maskedCreditCardNumber",
    "cvvFlag",
    "cvvResponseCode",
    "paymentCertificate",
    "paymentDateTime",
    "billingType",
    "responseCode",
    "transactionCondition",
    "currencyCode",
    "transmitionDateTime"
})
public class SipsPayment
    extends AbstractPayment
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String authorizationId;
    @XmlElement(required = true)
    protected BigInteger bankResponseCode;
    @XmlElement(required = true)
    protected String maskedCreditCardNumber;
    @XmlElement(required = true)
    protected BigInteger cvvFlag;
    @XmlElement(required = true)
    protected String cvvResponseCode;
    @XmlElement(required = true)
    protected String paymentCertificate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar paymentDateTime;
    @XmlElement(required = true)
    protected String billingType;
    @XmlElement(required = true)
    protected String responseCode;
    @XmlElement(required = true)
    protected String transactionCondition;
    @XmlElement(required = true)
    protected String currencyCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar transmitionDateTime;

    /**
     * Gets the value of the authorizationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationId() {
        return authorizationId;
    }

    /**
     * Sets the value of the authorizationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationId(String value) {
        this.authorizationId = value;
    }

    public boolean isSetAuthorizationId() {
        return (this.authorizationId!= null);
    }

    /**
     * Gets the value of the bankResponseCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBankResponseCode() {
        return bankResponseCode;
    }

    /**
     * Sets the value of the bankResponseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBankResponseCode(BigInteger value) {
        this.bankResponseCode = value;
    }

    public boolean isSetBankResponseCode() {
        return (this.bankResponseCode!= null);
    }

    /**
     * Gets the value of the maskedCreditCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaskedCreditCardNumber() {
        return maskedCreditCardNumber;
    }

    /**
     * Sets the value of the maskedCreditCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaskedCreditCardNumber(String value) {
        this.maskedCreditCardNumber = value;
    }

    public boolean isSetMaskedCreditCardNumber() {
        return (this.maskedCreditCardNumber!= null);
    }

    /**
     * Gets the value of the cvvFlag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCvvFlag() {
        return cvvFlag;
    }

    /**
     * Sets the value of the cvvFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCvvFlag(BigInteger value) {
        this.cvvFlag = value;
    }

    public boolean isSetCvvFlag() {
        return (this.cvvFlag!= null);
    }

    /**
     * Gets the value of the cvvResponseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCvvResponseCode() {
        return cvvResponseCode;
    }

    /**
     * Sets the value of the cvvResponseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCvvResponseCode(String value) {
        this.cvvResponseCode = value;
    }

    public boolean isSetCvvResponseCode() {
        return (this.cvvResponseCode!= null);
    }

    /**
     * Gets the value of the paymentCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentCertificate() {
        return paymentCertificate;
    }

    /**
     * Sets the value of the paymentCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentCertificate(String value) {
        this.paymentCertificate = value;
    }

    public boolean isSetPaymentCertificate() {
        return (this.paymentCertificate!= null);
    }

    /**
     * Gets the value of the paymentDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPaymentDateTime() {
        return paymentDateTime;
    }

    /**
     * Sets the value of the paymentDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPaymentDateTime(XMLGregorianCalendar value) {
        this.paymentDateTime = value;
    }

    public boolean isSetPaymentDateTime() {
        return (this.paymentDateTime!= null);
    }

    /**
     * Gets the value of the billingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillingType() {
        return billingType;
    }

    /**
     * Sets the value of the billingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillingType(String value) {
        this.billingType = value;
    }

    public boolean isSetBillingType() {
        return (this.billingType!= null);
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    public boolean isSetResponseCode() {
        return (this.responseCode!= null);
    }

    /**
     * Gets the value of the transactionCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionCondition() {
        return transactionCondition;
    }

    /**
     * Sets the value of the transactionCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionCondition(String value) {
        this.transactionCondition = value;
    }

    public boolean isSetTransactionCondition() {
        return (this.transactionCondition!= null);
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    public boolean isSetCurrencyCode() {
        return (this.currencyCode!= null);
    }

    /**
     * Gets the value of the transmitionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTransmitionDateTime() {
        return transmitionDateTime;
    }

    /**
     * Sets the value of the transmitionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTransmitionDateTime(XMLGregorianCalendar value) {
        this.transmitionDateTime = value;
    }

    public boolean isSetTransmitionDateTime() {
        return (this.transmitionDateTime!= null);
    }

}
