//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.order;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trackingProperty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trackingProperty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trackingPropertyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trackingPropertyValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trackingProperty", propOrder = {
    "trackingPropertyId",
    "trackingPropertyValue"
})
public class TrackingProperty
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String trackingPropertyId;
    @XmlElement(required = true)
    protected String trackingPropertyValue;

    /**
     * Gets the value of the trackingPropertyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingPropertyId() {
        return trackingPropertyId;
    }

    /**
     * Sets the value of the trackingPropertyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingPropertyId(String value) {
        this.trackingPropertyId = value;
    }

    public boolean isSetTrackingPropertyId() {
        return (this.trackingPropertyId!= null);
    }

    /**
     * Gets the value of the trackingPropertyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingPropertyValue() {
        return trackingPropertyValue;
    }

    /**
     * Sets the value of the trackingPropertyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingPropertyValue(String value) {
        this.trackingPropertyValue = value;
    }

    public boolean isSetTrackingPropertyValue() {
        return (this.trackingPropertyValue!= null);
    }

}
