//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//


package com.accurate.acec.invoiceinfo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.accurate.acec.invoiceinfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvoiceInfo_QNAME = new QName("http://www.accurate.com/acec/InvoiceInfo", "invoiceInfo");
    private final static QName _ObjectData_QNAME = new QName("http://www.accurate.com/acec/InvoiceInfo", "objectData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.accurate.acec.invoiceinfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceInfo }
     * 
     */
    public InvoiceInfo createInvoiceInfo() {
        return new InvoiceInfo();
    }

    /**
     * Create an instance of {@link ObjectData }
     * 
     */
    public ObjectData createObjectData() {
        return new ObjectData();
    }

    /**
     * Create an instance of {@link InvoiceInfo.ObjectDataList }
     * 
     */
    public InvoiceInfo.ObjectDataList createInvoiceInfoObjectDataList() {
        return new InvoiceInfo.ObjectDataList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/InvoiceInfo", name = "invoiceInfo")
    public JAXBElement<InvoiceInfo> createInvoiceInfo(InvoiceInfo value) {
        return new JAXBElement<InvoiceInfo>(_InvoiceInfo_QNAME, InvoiceInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.accurate.com/acec/InvoiceInfo", name = "objectData")
    public JAXBElement<ObjectData> createObjectData(ObjectData value) {
        return new JAXBElement<ObjectData>(_ObjectData_QNAME, ObjectData.class, null, value);
    }

}
