//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.26 at 05:00:48 AM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.accurate.com/acec/AcecBOSOAIntegration/BOOrderIntegration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.accurate.acec.acecbosoaintegration.boorderintegration;
